### ISSUE TITLE
Bonjour and global access broken after update

### ISSUE THREAD

**Issue by mschm** [experimental-platform/platform-configure-script#27]
Updating via Web Interface is known to currently not working, so I terminaled:

```
sudo /opt/bin/platform-configure --channel alpha
```

After that, the bonjour url doesn't work anymore, neither does myname.protonet.info.
Local IP still works.

**Comment by mschm** [comment]
after resetting experimental platform (deleting the data) at least bonjour works again.

**Comment by tiff** [comment]
I was just able to reproduce this issue by simply restarting the box. Both public address and bonjour weren't available.

seems like a bunch of microservices are not started anymore:

```
platform@tinker ~ $ docker ps
CONTAINER ID        IMAGE                                                COMMAND                CREATED             STATUS              PORTS                      NAMES
b08f475cb14e        experimentalplatform/frontend:alpha-testing          "/bin/sh -c 'node bi   2 minutes ago       Up 2 minutes        127.0.0.1:9002->3000/tcp   frontend
ae7d7ceec759        experimentalplatform/skvs:alpha-testing              "/skvs --port 80 --w   2 minutes ago       Up 2 minutes        80/tcp                     skvs
ce659ea2ad3e        experimentalplatform/ptw:alpha-testing               "start_publish_to_we   2 minutes ago       Up 2 minutes                                   ptw
4c955db78987        experimentalplatform/app-manager:alpha-testing       "/app-manager --port   2 minutes ago       Up 2 minutes        80/tcp                     app-manager
0c52fe80a998        experimentalplatform/systemd-proxy:alpha-testing     "/sproxy -port 80"     2 minutes ago       Up 2 minutes        80/tcp                     sproxy
4afd37fe9a99        experimentalplatform/monitoring:alpha-testing        "/monitoring --port    2 minutes ago       Up 2 minutes        80/tcp                     monitoring
3ab14cf87724        experimentalplatform/central-gateway:alpha-testing   "/central-gateway --   2 minutes ago       Up 2 minutes                                   central-gateway
```

digging into it.

**Comment by tiff** [comment]
More details:

```
platform@tinker ~ $ docker ps --all
CONTAINER ID        IMAGE                                                COMMAND                CREATED              STATUS                            PORTS                      NAMES
dc371aa75593        experimentalplatform/frontend:alpha-testing          "/bin/sh -c 'node bi   55 seconds ago       Up 52 seconds                     127.0.0.1:9002->3000/tcp   frontend
99b33da08fb2        experimentalplatform/ptw:alpha-testing               "start_publish_to_we   56 seconds ago       Up 56 seconds                                                ptw
0c08dea985b3        experimentalplatform/skvs:alpha-testing              "/skvs --port 80 --w   57 seconds ago       Up 56 seconds                     80/tcp                     skvs
aeaeabcd193d        experimentalplatform/central-gateway:alpha-testing   "/central-gateway --   59 seconds ago       Up 58 seconds                                                central-gateway
b91adfe2eaee        experimentalplatform/systemd-proxy:alpha-testing     "/sproxy -port 80"     About a minute ago   Up 59 seconds                     80/tcp                     sproxy
829f84a1d2a0        experimentalplatform/app-manager:alpha-testing       "/app-manager --port   About a minute ago   Up About a minute                 80/tcp                     app-manager
97ffe27aee2e        experimentalplatform/monitoring:alpha-testing        "/monitoring --port    About a minute ago   Up About a minute                 80/tcp                     monitoring
168f9cf1d500        experimentalplatform/hostname-smb:alpha-testing      "/usr/sbin/nmbd -F -   3 minutes ago        Exited (137) About a minute ago                              hostname-smb
c2a45cff2356        experimentalplatform/hostname-avahi:alpha-testing    "/bin/bash -c 'sleep   3 minutes ago        Exited (137) About a minute ago                              hostname-avahi
26a53d795910        experimentalplatform/dokku:alpha-testing             "start_dokku"          3 minutes ago        Exited (137) About a minute ago                              dokku
d65ab0932abb        dokku/foobar:latest                                  "/start web"           35 minutes ago       Exited (2) 34 minutes ago                                    high_meitner
a09808ecb2de        dokku/foobar:latest                                  "/bin/bash -c 'mkdir   35 minutes ago       Exited (0) 35 minutes ago                                    ecstatic_darwin
88fb716da98d        dokku/foobar:latest                                  "/build/builder"       35 minutes ago       Exited (0) 35 minutes ago                                    tender_stallman
559c66c8d1bb        dokku/foobar:latest                                  "/bin/bash -c 'cat >   35 minutes ago       Exited (0) 35 minutes ago                                    elegant_albattani
ae0b3f70de93        dokku/foobar:latest                                  "\"/bin/bash -c 'for   35 minutes ago       Exited (0) 35 minutes ago                                    clever_ardinghelli
fcc4120e9266        experimentalplatform/buildstep:latest                "/bin/buildapp.sh"     36 minutes ago       Exited (0) 36 minutes ago                                    insane_babbage
db9025b41b99        dokku/toilet-status:latest                           "/start web"           About an hour ago    Exited (2) 33 minutes ago                                    berserk_heisenberg
5ae5ddacfc8c        dokku/permission-test:latest                         "\"/bin/bash -c 'for   11 days ago          Dead                                                         lonely_torvalds
```

docker logs for smb microservice:

```
platform@tinker ~ $ docker logs 168f9cf1d500
nmbd version 4.1.13-Ubuntu started.
Copyright Andrew Tridgell and the Samba Team 1992-2013
standard input is not a socket, assuming -D option
STATUS=daemon 'nmbd' finished starting up and ready to serve connections*****

Samba name server TINKER is now a local master browser for workgroup PROTONET on subnet 172.17.42.1

*****
Got SIGTERM: going down...
```

docker logs for avahi microservice:

```
platform@tinker ~ $ docker logs c2a45cff2356
Found user 'avahi' (UID 105) and group 'avahi' (GID 109).
Successfully dropped root privileges.
avahi-daemon 0.6.31 starting up.
Successfully called chroot().
Successfully dropped remaining capabilities.
No service file found in /etc/avahi/services.
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.42.1.
New relevant interface docker0.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::9421:89ff:fe63:dcf1 on docker0.*.
Registering new address record for 172.17.42.1 on docker0.IPv4.
Registering new address record for fe80::7ed3:aff:fe11:8e6e on enp1s0.*.
Registering HINFO record with values 'X86_64'/'LINUX'.
Server startup complete. Host name is tinker.local. Local service cookie is 1999733932.
Withdrawing workstation service for veth14ae4fd.
Joining mDNS multicast group on interface enp1s0.IPv4 with address 172.16.10.134.
New relevant interface enp1s0.IPv4 for mDNS.
Registering new address record for 172.16.10.134 on enp1s0.IPv4.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Invalid response packet from host 172.16.10.106.
Got SIGTERM, quitting.
```

every following reboot I did, wasn't fixing that problem.

**Comment by tiff** [comment]
@mschm We shipped a [new release today](https://github.com/experimental-platform/platform-configure-script/blob/master/CHANGELOG.md). Please update your box via command line and try again. Thank you!

**Comment by mschm** [comment]
My box still cannot be reached via skylabs.protonet.info

This is what avahi microservice says:

```
platform@skylabs ~ $ docker logs eb639bcc50ba
Found user 'avahi' (UID 105) and group 'avahi' (GID 109).
Successfully dropped root privileges.
avahi-daemon 0.6.31 starting up.
Successfully called chroot().
Successfully dropped remaining capabilities.
No service file found in /etc/avahi/services.
Joining mDNS multicast group on interface docker0.IPv4 with address 172.17.42.1.
New relevant interface docker0.IPv4 for mDNS.
Joining mDNS multicast group on interface enp1s0.IPv4 with address 192.168.7.100.
New relevant interface enp1s0.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::14de:d8ff:fe2b:eca2 on veth904c145.*.
Registering new address record for fe80::f801:38ff:fe3a:8637 on vethb9160ad.*.
Registering new address record for fe80::f45e:5eff:fe43:95d6 on veth0f6a107.*.
Registering new address record for fe80::e45b:94ff:fe9f:60b9 on veth6ffe7f5.*.
Registering new address record for fe80::e404:4cff:fe48:5771 on vethc7ca405.*.
Registering new address record for fe80::ccec:40ff:fea3:54dc on veth68392a3.*.
Registering new address record for fe80::78de:25ff:fe43:fb5d on docker0.*.
Registering new address record for 172.17.42.1 on docker0.IPv4.
Registering new address record for fe80::7ed3:aff:fe11:5ec9 on enp1s0.*.
Registering new address record for 192.168.7.100 on enp1s0.IPv4.
Server startup complete. Host name is skylabs.local. Local service cookie is 3537834240.
Registering HINFO record with values 'X86_64'/'LINUX'.
Withdrawing workstation service for veth943e722.
Withdrawing workstation service for veth943e722.
Withdrawing workstation service for vethb10f75d.
Withdrawing workstation service for veth7843439.
Withdrawing workstation service for veth7843439.
Withdrawing workstation service for veth82da1f6.
Withdrawing workstation service for veth5f44694.
Withdrawing workstation service for veth5f44694.
Withdrawing workstation service for veth6a245e9.
Withdrawing workstation service for veth294a36d.
Withdrawing workstation service for veth294a36d.
Withdrawing workstation service for veth57f8a76.
Withdrawing workstation service for veth48cef6e.
Withdrawing workstation service for veth48cef6e.
Withdrawing workstation service for vethadeda47.
Withdrawing workstation service for veth2ba0959.
Withdrawing workstation service for veth2ba0959.
Withdrawing workstation service for veth62a1c27.
Withdrawing workstation service for vethec28013.
Withdrawing workstation service for vethec28013.
Withdrawing workstation service for veth40810d8.
Withdrawing workstation service for vethed8eb9f.
Withdrawing workstation service for vethed8eb9f.
Withdrawing workstation service for veth101a487.
Withdrawing workstation service for vetha92109e.
Withdrawing workstation service for vetha92109e.
Withdrawing workstation service for vethdcf774b.
Withdrawing workstation service for veth16e15e1.
Withdrawing workstation service for veth16e15e1.
Withdrawing workstation service for veth26cdad0.
Withdrawing workstation service for veth0df2058.
Withdrawing workstation service for veth0df2058.
Withdrawing workstation service for veth27cbceb.
Withdrawing workstation service for vethf8438c1.
Withdrawing workstation service for vethf8438c1.
Withdrawing workstation service for vetha07d13a.
Withdrawing workstation service for veth496cfcf.
Withdrawing workstation service for veth496cfcf.
Withdrawing workstation service for vethbeb354e.
Withdrawing workstation service for veth5544107.
Withdrawing workstation service for veth5544107.
Withdrawing workstation service for vethd24035b.
Withdrawing workstation service for vethddc8af5.
Withdrawing workstation service for vethddc8af5.
Withdrawing workstation service for vethab19073.
Withdrawing workstation service for veth3997527.
Withdrawing workstation service for veth3997527.
Withdrawing workstation service for veth1e64e70.
Withdrawing workstation service for vethe06e600.
Withdrawing workstation service for vethe06e600.
Withdrawing workstation service for vetha8a2af3.
Withdrawing workstation service for veth180a8c5.
Withdrawing workstation service for veth180a8c5.
Withdrawing workstation service for veth46e043d.
Withdrawing workstation service for veth87ae8ee.
Withdrawing workstation service for veth87ae8ee.
Withdrawing workstation service for vethf0ba6f0.
Withdrawing workstation service for vethfe3d9ec.
Withdrawing workstation service for vethfe3d9ec.
Withdrawing workstation service for veth503bb78.
Withdrawing workstation service for vethd555772.
Withdrawing workstation service for vethd555772.
Withdrawing workstation service for veth3f266ee.
Withdrawing workstation service for vethdb66199.
Withdrawing workstation service for vethdb66199.
Withdrawing workstation service for veth58a98f1.
Withdrawing workstation service for veth0f24661.
Withdrawing workstation service for veth0f24661.
Withdrawing workstation service for veth3f00b38.
Withdrawing workstation service for veth3a312fc.
Withdrawing workstation service for veth3a312fc.
Withdrawing workstation service for vetha0d68ff.
Withdrawing workstation service for veth18029cb.
Withdrawing workstation service for veth18029cb.
Withdrawing workstation service for vethf643d23.
Withdrawing workstation service for veth437d5e2.
Withdrawing workstation service for veth437d5e2.
Withdrawing workstation service for vethdec15b6.
Withdrawing workstation service for vethbbca30b.
Withdrawing workstation service for vethbbca30b.
Withdrawing workstation service for veth19d11c2.
Withdrawing workstation service for veth7339d5c.
Withdrawing workstation service for veth7339d5c.
Withdrawing workstation service for veth3d72f07.
Withdrawing workstation service for veth21910d7.
Withdrawing workstation service for veth21910d7.
Withdrawing workstation service for vethb5f56f4.
Withdrawing workstation service for vethe088fdd.
Withdrawing workstation service for vethcca1a8e.
Withdrawing workstation service for vethcca1a8e.
Withdrawing workstation service for vethaf0864c.
Withdrawing workstation service for vethe088fdd.
Withdrawing workstation service for veth3956abf.
Withdrawing workstation service for veth8a90e40.
Withdrawing workstation service for veth8a90e40.
Withdrawing workstation service for vethbf8094c.
Withdrawing workstation service for veth7adfb57.
Withdrawing workstation service for veth7adfb57.
Withdrawing workstation service for vetha5f7005.
Withdrawing workstation service for veth27b448c.
Registering new address record for fe80::1cb0:f3ff:fead:dddf on veth2c6da65.*.
Withdrawing workstation service for veth6642619.
Withdrawing workstation service for veth6642619.
Withdrawing workstation service for vethaa40d68.
Withdrawing address record for fe80::1cb0:f3ff:fead:dddf on veth2c6da65.
Withdrawing workstation service for veth27b448c.
Withdrawing workstation service for veth2c6da65.
Withdrawing workstation service for vethb685b78.
Withdrawing workstation service for vethb685b78.
Withdrawing workstation service for veth2d4c76a.
Withdrawing workstation service for vethb2537d3.
Withdrawing workstation service for vethb2537d3.
Withdrawing workstation service for vethf486bdb.
Withdrawing workstation service for veth193d552.
Withdrawing workstation service for veth193d552.
Withdrawing workstation service for veth4a68a78.
```

and so on

**Comment by tiff** [comment]
is at least bonjour `skylabs.local` working now?

**Comment by mschm** [comment]
Bonjour is fine

**Comment by tiff** [comment]
what does `docker logs ptw` say? (ptw is the microservice that ensures that the box is available on the internet)

**Comment by mschm** [comment]
ptw seems to be missing?

```
platform@skylabs ~ $ docker ps -a
CONTAINER ID        IMAGE                                                COMMAND                CREATED             STATUS                    PORTS                                          NAMES
9968fd08daf0        experimentalplatform/hostname-smb:alpha-testing      "/usr/sbin/nmbd -F -   53 minutes ago      Up 53 minutes                                                            hostname-smb        
74ae2f471047        experimentalplatform/hostname-avahi:alpha-testing    "/bin/bash -c 'sleep   53 minutes ago      Up 53 minutes                                                            hostname-avahi      
00b0378eef8a        dokku/nodejs-hello-world                             "/start web"           12 hours ago        Up 12 hours                                                              romantic_hypatia    
3a7508c69d49        dokku/nodejs-hello-world                             "/bin/bash -c 'mkdir   12 hours ago        Exited (0) 12 hours ago                                                  tender_ritchie      
13d017268484        dokku/nodejs-hello-world                             "/bin/bash -c 'mkdir   12 hours ago        Exited (0) 12 hours ago                                                  lonely_galileo      
3b61e78724ce        dokku/nodejs-hello-world                             "/build/builder"       12 hours ago        Exited (0) 12 hours ago                                                  naughty_poincare    
876d5b5bcd87        dokku/nodejs-hello-world                             "/bin/bash -e -c 'ex   12 hours ago        Exited (0) 12 hours ago                                                  prickly_ptolemy     
f417d42b59d0        dokku/nodejs-hello-world                             "/bin/bash -c 'cat >   12 hours ago        Exited (0) 12 hours ago                                                  admiring_pare       
898911b56229        dokku/nodejs-hello-world                             "/bin/bash -c 'for E   12 hours ago        Exited (0) 12 hours ago                                                  reverent_poincare   
fa6152ab97aa        experimentalplatform/buildstep                       "/bin/buildapp.sh"     12 hours ago        Exited (0) 12 hours ago                                                  reverent_wozniak    
9ac8e3153d12        experimentalplatform/frontend:alpha-testing          "/bin/sh -c 'node bi   12 hours ago        Up 12 hours               127.0.0.1:9002->3000/tcp                       frontend            
e755dfe7d276        experimentalplatform/skvs:alpha-testing              "/skvs --port 80 --w   12 hours ago        Up 12 hours               80/tcp                                         skvs                
7a75cf66983a        experimentalplatform/central-gateway:alpha-testing   "/central-gateway --   12 hours ago        Up 12 hours                                                              central-gateway     
966be2c830d0        experimentalplatform/monitoring:alpha-testing        "/monitoring --port    12 hours ago        Up 12 hours               80/tcp                                         monitoring          
d09d1e798bce        experimentalplatform/app-manager:alpha-testing       "/app-manager --port   12 hours ago        Up 12 hours               80/tcp                                         app-manager         
29786ed0f33f        experimentalplatform/dokku:alpha-testing             "start_dokku"          12 hours ago        Up 12 hours               0.0.0.0:8022->22/tcp, 127.0.0.1:9001->80/tcp   dokku               
18fd290cdfd3        experimentalplatform/systemd-proxy:alpha-testing     "/sproxy -port 80"     12 hours ago        Up 12 hours               80/tcp                                         sproxy
```

**Comment by hinnerk** [comment]
Could you please try `sudo systemctl status ptw-protonet.service` and possibly `sudo journalctl -u ptw-protonet.service`? It should tell us why ptw doesn't come up.

**Comment by mschm** [comment]
here we go:

```
platform@skylabs ~ $ sudo systemctl status ptw-protonet.service
● ptw-protonet.service - Run 'ptw' service
   Loaded: loaded (/etc/systemd/system/ptw-protonet.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) since Thu 2015-08-27 10:18:27 UTC; 8s ago
 Main PID: 23838
```

and:

```
platform@skylabs ~ $ sudo journalctl -u ptw-protonet.service
-- Logs begin at Wed 2015-08-26 22:29:09 UTC, end at Thu 2015-08-27 10:19:50 UTC. --
Aug 26 22:29:09 skylabs systemd-docker[25163]: 2015/08/26 22:29:09 Moving pid 25185 to /sys/fs/cgroup/systemd/system.slice/ptw-protonet.service/cgroup.procs
Aug 26 22:29:09 skylabs systemd[1]: ptw-protonet.service: Supervising process 25185 which is not our child. We'll most likely not notice when it exits.
Aug 26 22:29:09 skylabs systemd[1]: Started Run 'ptw' service.
Aug 26 22:29:09 skylabs systemd-docker[25163]: platform.7f387c380b92.ensure_identifier_exists: 0
Aug 26 22:29:10 skylabs systemd-docker[25163]: platform.7f387c380b92.PublishToWeb.info: 1
Aug 26 22:29:10 skylabs systemd-docker[25163]: /usr/local/bundle/gems/publish_to_web-1.1.0/lib/publish_to_web.rb:42:in `call': ["invalid node name"] (ArgumentError)
Aug 26 22:29:10 skylabs systemd-docker[25163]: from /usr/local/bundle/gems/publish_to_web-1.1.0/lib/publish_to_web.rb:179:in `set_node_name'
Aug 26 22:29:10 skylabs systemd-docker[25163]: from /bin/start_publish_to_web:67:in `<main>'
Aug 26 22:29:20 skylabs systemd[1]: ptw-protonet.service: Service hold-off time over, scheduling restart.
Aug 26 22:29:20 skylabs systemd[1]: Starting Run 'ptw' service...
Aug 26 22:29:20 skylabs systemd-docker[25207]: 2015/08/26 22:29:20 Moving pid 25229 to /sys/fs/cgroup/systemd/system.slice/ptw-protonet.service/cgroup.procs
Aug 26 22:29:20 skylabs systemd[1]: ptw-protonet.service: Supervising process 25229 which is not our child. We'll most likely not notice when it exits.
Aug 26 22:29:20 skylabs systemd[1]: Started Run 'ptw' service.
Aug 26 22:29:20 skylabs systemd-docker[25207]: platform.8c7c5bf1292e.ensure_identifier_exists: 0
Aug 26 22:29:20 skylabs systemd-docker[25207]: platform.8c7c5bf1292e.PublishToWeb.info: 0
Aug 26 22:29:21 skylabs systemd-docker[25207]: /usr/local/bundle/gems/publish_to_web-1.1.0/lib/publish_to_web.rb:42:in `call': ["invalid node name"] (ArgumentError)
Aug 26 22:29:21 skylabs systemd-docker[25207]: from /usr/local/bundle/gems/publish_to_web-1.1.0/lib/publish_to_web.rb:179:in `set_node_name'
Aug 26 22:29:21 skylabs systemd-docker[25207]: from /bin/start_publish_to_web:67:in `<main>'
Aug 26 22:29:31 skylabs systemd[1]: ptw-protonet.service: Service hold-off time over, scheduling restart.
Aug 26 22:29:31 skylabs systemd[1]: Starting Run 'ptw' service...
Aug 26 22:29:31 skylabs systemd-docker[25261]: 2015/08/26 22:29:31 Moving pid 25281 to /sys/fs/cgroup/systemd/system.slice/ptw-protonet.service/cgroup.procs
```

(repeating)

**Comment by tiff** [comment]
https://skylabs.protonet.info/ is now working. I had to delete an old publication in our infrastructure.
The box is generating a new license on reset (that's what you did). A license is bound to the box-name. So the name was kind of already "taken" by another box (that didn't exist anymore since you did a reset).
I created another issue #36 for proper error handling in the web gui

**Comment by mschm** [comment]
Hooray :) that's awesome, thanks!
And please – could you also reset vskylabs.protonet.info? That's a virtual machine, same problem there...

**Comment by tiff** [comment]
@mschm sure. done!
