### ISSUE TITLE
Pushing fails

### ISSUE THREAD

**Issue by mgrsskls** [experimental-platform/platform-configure-script#8]
I created a rails app according to the example. Pushing to the remote fails.

```
Counting objects: 64, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (51/51), done.
Writing objects: 100% (64/64), 16.20 KiB | 0 bytes/s, done.
Total 64 (delta 2), reused 64 (delta 2)
-----> Cleaning up...
-----> Building hello-world from buildstep...
-----> Adding BUILD_ENV to build environment...
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.0.0
-----> Installing dependencies using 1.6.3
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Using i18n 0.7.0
       Using minitest 5.7.0
       Using thread_safe 0.3.5
       Using builder 3.2.2
       Using erubis 2.7.0
       Using mini_portile 0.6.2
       Using rack 1.6.4
       Using mime-types 2.6.1
       Using arel 6.0.2
       Using coffee-script-source 1.9.1.1
       Using execjs 2.5.2
       Using thor 0.19.1
       Using multi_json 1.11.2
       Using bundler 1.6.3
       Using sass 3.4.16
       Using tilt 1.4.1
       Using sqlite3 1.3.10
       Using tzinfo 1.2.2
       Using nokogiri 1.6.6.2
       Using rack-test 0.6.3
       Using sprockets 3.2.0
       Using mail 2.6.3
       Using coffee-script 2.4.1
       Using loofah 2.0.2
       Using rails-html-sanitizer 1.0.2
       Using rake 10.4.2
       Using json 1.8.3
       Using activesupport 4.2.3
       Using uglifier 2.7.1
       Using rails-deprecated_sanitizer 1.0.3
       Using globalid 0.3.5
       Using activemodel 4.2.3
       Using rails-dom-testing 1.0.6
       Using rdoc 4.2.0
       Using activerecord 4.2.3
       Using jbuilder 2.3.1
       Using activejob 4.2.3
       Using actionview 4.2.3
       Using sdoc 0.4.1
       Using actionpack 4.2.3
       Using actionmailer 4.2.3
       Using railties 4.2.3
       Using sprockets-rails 2.3.2
       Using jquery-rails 4.0.4
       Using coffee-rails 4.1.0
       Using rails 4.2.3
       Using sass-rails 5.0.3
       Using turbolinks 2.5.3
       Your bundle is complete!
       Gems in the groups development and test were not installed.
       It was installed into ./vendor/bundle
       Bundle completed (0.64s)
       Cleaning up the bundler cache.
       !
       !     Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 5 --max-time 30 http://nodejs.org/dist/v0.10.30/node-v0.10.30-linux-x64.tar.gz -s -o - | tar zxf - node-v0.10.30-linux-x64/bin/node' failed unexpectedly:
       !     tar: Skipping to next header
       !
       !     gzip: stdin: invalid compressed data--format violated
       !     tar: Child died with signal 13
       !     tar: Error is not recoverable: exiting now
       !
remote: /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/shell_helpers.rb:49:in `run!': Command: 'set -o pipefail; curl --fail --retry 3 --retry-delay 1 --connect-timeout 5 --max-time 30 http://nodejs.org/dist/v0.10.30/node-v0.10.30-linux-x64.tar.gz -s -o - | tar zxf - node-v0.10.30-linux-x64/bin/node' failed unexpectedly: (LanguagePack::Fetcher::FetchError)
remote: tar: Skipping to next header
remote:
remote: gzip: stdin: invalid compressed data--format violated
remote: tar: Child died with signal 13
remote: tar: Error is not recoverable: exiting now
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/fetcher.rb:24:in `fetch_untar'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/helpers/node_installer.rb:39:in `install'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:404:in `block in install_binary'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:402:in `chdir'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:402:in `install_binary'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:391:in `block (2 levels) in install_binaries'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:391:in `each'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:391:in `block in install_binaries'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote:     from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:47:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:43:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:390:in `install_binaries'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:97:in `block (2 levels) in compile'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:672:in `call'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:672:in `allow_git'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:92:in `block in compile'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote:     from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:47:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:43:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/ruby.rb:83:in `compile'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/rails2.rb:49:in `block in compile'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote:     from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:47:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:43:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/rails2.rb:47:in `compile'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/rails3.rb:38:in `block in compile'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote:     from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:47:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:43:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/rails3.rb:37:in `compile'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/rails4.rb:41:in `block in compile'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote:     from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:47:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:43:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/rails4.rb:40:in `compile'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/bin/compile:16:in `block (2 levels) in <main>'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/base.rb:124:in `log'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/bin/compile:15:in `block in <main>'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:35:in `call'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:35:in `block in trace'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:17:in `block in instrument'
remote:     from /usr/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:16:in `instrument'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/lib/language_pack/instrument.rb:35:in `trace'
remote:     from /tmp/buildpacks/heroku-buildpack-ruby/bin/compile:11:in `<main>'
To ssh://dokku@192.168.1.17:8022/hello-world
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://dokku@192.168.1.17:8022/hello-world'
```

~~Don't know if it would be fixed after a successful update. The update process is still running. See #7 :)~~ No, still not working.

**Comment by mgrsskls** [comment]
Pushing a PHP project works without problems.

**Comment by dbanck** [comment]
Working fine for me:

```
Counting objects: 64, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (53/53), done.
Writing objects: 100% (64/64), 16.20 KiB | 0 bytes/s, done.
Total 64 (delta 2), reused 0 (delta 0)
-----> Cleaning up...
-----> Building rails-test from buildstep...
-----> Adding BUILD_ENV to build environment...
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.0.0
-----> Installing dependencies using 1.6.3
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from https://rubygems.org/...........
       Fetching additional metadata from https://rubygems.org/..
       Installing i18n 0.7.0
       Installing rake 10.4.2
       Installing minitest 5.7.0
       Installing thread_safe 0.3.5
       Installing builder 3.2.2
       Installing erubis 2.7.0
       Installing mini_portile 0.6.2
       Installing json 1.8.3
       Installing rack 1.6.4
       Installing arel 6.0.2
       Installing mime-types 2.6.1
       Installing coffee-script-source 1.9.1.1
       Installing execjs 2.5.2
       Using bundler 1.6.3
       Installing thor 0.19.1
       Installing multi_json 1.11.2
       Installing tilt 1.4.1
       Installing sass 3.4.16
       Installing tzinfo 1.2.2
       Installing rdoc 4.2.0
       Installing rack-test 0.6.3
       Installing sqlite3 1.3.10
       Installing sprockets 3.2.0
       Installing mail 2.6.3
       Installing coffee-script 2.4.1
       Installing uglifier 2.7.1
       Installing activesupport 4.2.3
       Installing sdoc 0.4.1
       Installing rails-deprecated_sanitizer 1.0.3
       Installing globalid 0.3.5
       Installing activemodel 4.2.3
       Installing jbuilder 2.3.1
       Installing activejob 4.2.3
       Installing activerecord 4.2.3
       Installing nokogiri 1.6.6.2
       Installing rails-dom-testing 1.0.6
       Installing loofah 2.0.2
       Installing rails-html-sanitizer 1.0.2
       Installing actionview 4.2.3
       Installing actionpack 4.2.3
       Installing sprockets-rails 2.3.2
       Installing actionmailer 4.2.3
       Installing railties 4.2.3
       Installing coffee-rails 4.1.0
       Installing jquery-rails 4.0.4
       Installing rails 4.2.3
       Installing sass-rails 5.0.3
       Installing turbolinks 2.5.3
       Your bundle is complete!
       Gems in the groups development and test were not installed.
       It was installed into ./vendor/bundle
       Post-install message from rdoc:
       Depending on your version of ruby, you may need to install ruby rdoc/ri data:
       <= 1.8.6 : unsupported
       = 1.8.7 : gem install rdoc-data; rdoc-data --install
       = 1.9.1 : gem install rdoc-data; rdoc-data --install
       >= 1.9.2 : nothing to do! Yay!
       Bundle completed (42.16s)                                                                                                                                                                   
       Cleaning up the bundler cache.
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       I, [2015-08-05T20:31:22.530255 #808]  INFO -- : Writing /tmp/build/public/assets/application-744feb58c517097a41b7e0e121dd6e8316249f645d49af1e203d3164794489e5.js
       I, [2015-08-05T20:31:22.539500 #808]  INFO -- : Writing /tmp/build/public/assets/application-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css
       Asset precompilation completed (6.46s)
       Cleaning assets
       Running: rake assets:clean

       ###### WARNING:
       Include 'rails_12factor' gem to enable all platform features
       See https://devcenter.heroku.com/articles/rails-integration-gems for more information.

       ###### WARNING:
       You have not declared a Ruby version in your Gemfile.
       To set your Ruby version add this line to your Gemfile:
       ruby '2.0.0'
       # See https://devcenter.heroku.com/articles/ruby-versions for more information.

       ###### WARNING:
       No Procfile detected, using the default web server (webrick)
       https://devcenter.heroku.com/articles/ruby-default-web-server

-----> Discovering process types
       Default types for  -> worker, rake, console, web
-----> Releasing rails-test...
-----> Deploying rails-test...
-----> DOKKU_SCALE not found in app image. Defaulting to a single web process
-----> New DOKKU_SCALE file generated
=====> web=1
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://progrium.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
=====> rails-test container output:
       [2015-08-05 20:31:47] INFO  WEBrick 1.3.1
       [2015-08-05 20:31:47] INFO  ruby 2.0.0 (2015-04-13) [x86_64-linux]
       [2015-08-05 20:31:47] INFO  WEBrick::HTTPServer#start: pid=134 port=5000
=====> end rails-test container output
-----> Running post-deploy
-----> Creating new /data/rails-test/VHOST...
-----> Configuring zeus/rails-test...
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
=====> Application deployed
```

Why is your bundle this fast `Bundle completed (0.64s)` and not installing things?

**Comment by mgrsskls** [comment]
I tried it multiple times, so the gems were already installed.

**Comment by mgrsskls** [comment]
After using a different repository it works. I guess it was really caused by the failing update.

**Comment by tiff** [comment]
@mgrossklaus is this resolved for you?

**Comment by mgrsskls** [comment]
Jip, but I didn't want to close the issue because I was not sure if it was really caused by the failing update and if you want to have a look at it :)

**Comment by tiff** [comment]
:+1:
